name: Generate Sitemap
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://jacekstrzalkowski.pl"
      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap"
          git push
